# Run unit tests and formatting for the NiftyLittlePenguin repo.

name: NiftyLittlePenguin

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events only when there are changes in the desired paths
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        # Use bash as the shell
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - 
        name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/root/.local/bin:$PATH"
          export PATH="/home/your_username/.local/bin:$PATH"
          poetry install
      -
        name: Test with pytest
        run: |
          make test
      -
        name: Format with black and isort
        run: |
          make format